package com.semantalytics.jena.function.string;

import com.google.common.io.Files;
import junit.framework.TestCase;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import java.io.File;
import java.io.IOException;
import java.net.InetSocketAddress;

@RunWith(Suite.class)
@SuiteClasses({
  	TestAbbreviate.class,
	TestAbbreviateMiddle.class,
	TestAbbreviateWithMarker.class,
	TestAppendIfMissing.class,
	TestAppendIfMissingIgnoreCase.class,
    TestArrayFunctionSeparator.class,
    TestArrayPropertyFunction.class,
	TestCapitalize.class,
	TestCaseFormat.class,
	TestCenter.class,
	TestChomp.class,
	TestChop.class,
	TestCommonPrefix.class,
	TestCommonSuffix.class,
	TestCompare.class,
	TestCompareIgnoreCase.class,
	TestContains.class,
	TestContainsAny.class,
	TestContainsIgnoreCase.class,
	TestContainsNone.class,
	TestContainsOnly.class,
	TestContainsWhitespace.class,
	TestCountMatches.class,
	TestDefaultIfBlank.class,
	TestDefaultIfEmpty.class,
	TestDeleteWhitespace.class,
	TestDifference.class,
	TestDigits.class,
	TestEndsWith.class,
	TestEndsWithIgnoreCase.class,
	TestEquals.class,
	TestEqualsAny.class,
	TestEqualsIgnoreCase.class,
	TestIndexOf.class,
	TestIndexOfAny.class,
	TestIndexOfAnyBut.class,
	TestIndexOfDifference.class,
	TestIndexOfIgnoreCase.class,
	TestInitials.class,
	TestIsAllBlank.class,
	TestIsAllLowerCase.class,
	TestIsAllUpperCase.class,
	TestIsAlpha.class,
	TestIsAlphaSpace.class,
	TestIsAlphanumeric.class,
	TestIsAlphanumericSpace.class,
	TestIsAnyBlank.class,
	TestIsAnyEmpty.class,
	TestIsAsciiPrintable.class,
	TestIsBlank.class,
	TestIsEmpty.class,
	TestIsMixedCase.class,
	TestIsNoneBlank.class,
	TestIsNoneEmpty.class,
	TestIsNotBlank.class,
	TestIsNotEmpty.class,
	TestIsNumeric.class,
	TestIsNumericSpace.class,
	TestIsWhitespace.class,
	TestJoin.class,
    TestJoinArray.class,
	TestJoinWith.class,
    TestJoinArrayWith.class,
	TestLastIndexOf.class,
	TestLastIndexOfAny.class,
	TestLastIndexOfIgnoreCase.class,
	TestLastOrdinalIndexOf.class,
	TestLeft.class,
	TestLeftPad.class,
	TestLength.class,
	TestLowerCase.class,
	TestMid.class,
	TestNormalizeSpace.class,
	TestOrdinalIndexOf.class,
	TestOverlay.class,
	TestPadEnd.class,
	TestPadStart.class,
	TestPrependIfMissing.class,
	TestPrependIfMissingIgnoreCase.class,
	TestRemove.class,
	TestRemoveAll.class,
	TestRemoveEnd.class,
	TestRemoveEndIgnoreCase.class,
	TestRemoveFirst.class,
	TestRemoveIgnoreCase.class,
	TestRemovePattern.class,
	TestRemoveStart.class,
	TestRemoveStartIgnoreCase.class,
	TestRepeat.class,
	TestReplace.class,
	TestReplaceAll.class,
	TestReplaceChars.class,
	TestReplaceEach.class,
	TestReplaceEachRepeatedly.class,
	TestReplaceFirst.class,
	TestReplaceIgnoreCase.class,
	TestReplaceOnce.class,
	TestReplaceOnceIgnoreCase.class,
	TestReplacePattern.class,
	TestReverse.class,
	TestReverseDelimited.class,
	TestRight.class,
	TestRightPad.class,
	TestRotate.class,
	TestSplit.class,
	TestSplitByCharacterType.class,
    TestSplitByCharacterTypeCamelCase.class,
	TestStartsWith.class,
	TestStartsWithAny.class,
	TestStartsWithIgnoreCase.class,
	TestStrip.class,
	TestStripAccents.class,
	TestStripAll.class,
	TestStripEnd.class,
	TestStripStart.class,
	TestSubstringAfterLast.class,
	TestSubstring.class,
	TestSubstringAfter.class,
	TestSubstringBefore.class,
	TestSubstringBeforeLast.class,
	TestSubstringBetween.class,
	TestSwapCase.class,
	TestTrim.class,
	TestTruncate.class,
	TestUncapitalize.class,
	TestUnwrap.class,
	TestUpperCase.class,
	TestWrap.class,
	TestWrapIfMissing.class
})

public class StringTestSuite extends TestCase {
}
